version: 0.0
Resources:
  - SabsLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "sabs-lambda"
        Alias: "live" # Specify the alias for your Lambda function
        CurrentVersion: "$LATEST" # Specify the current version of your Lambda function
        TargetVersion: "1"