version: 0.2
        
phases:
  pre_build:
    commands:
      - echo "Creating Lambda package..."
  build:
    commands:
      - pip3 install -r requirements.txt -t .
      - echo "Package created..."
  post_build:
    commands:
      - echo "Package created..."
artifacts:
  files:
    - "*/**"
  name: lambda_dep
  exclude-paths:
    - buildspec.yml
      