version: 0.2
        
phases:
  pre_build:
    commands:
      - echo "Creating Lambda package..."
  build:
    commands:
      - pip3 install -r requirements.txt -t .
      - zip -r lambda_dep.zip . -x "buildspec.yml" -x "appspec.yml"
      - ls -larth
      - echo "Package created..."
  post_build:
    commands:
      - aws lambda update-function-code --function-name sabs-lambda --zip-file fileb://lambda_dep.zip
      - CURRENT_VERSION=$(aws lambda get-alias --function-name sabs-lambda --name live --query 'FunctionVersion' --output text)
      - echo "Current alias points to version $CURRENT_VERSION"
      - TARGET_VERSION=$(aws lambda publish-version --function-name sabs-lambda --query 'Version' --output text)
      - echo "Published version $TARGET_VERSION"
      - sed -i "s/Current_Version/$CURRENT_VERSION/g" appspec.yml
      - sed -i "s/Target_Version/$TARGET_VERSION/g" appspec.yml
      - cat appspec.yml
      - echo "Function code updated and appspec created..."

artifacts:
  files:
    - appspec.yml
    - lambda_dep.zip
