version: 0.2
        
phases:
  pre_build:
    commands:
      - echo "Creating Lambda package..."
  build:
    commands:
      - pip3 install -r requirements.txt -t .
      - zip -r lambda_dep.zip . -x "buildspec.yml" -x "appspec.yml"
      - ls -larth
      - echo "Package created..."
  post_build:
    commands:
      - aws lambda update-function-code --function-name sabs-lambda --zip-file fileb://lambda_dep.zip
      - NEW_VERSION=$(aws lambda publish-version --function-name sabs-lambda --query 'Version' --output text)
      - echo "Published version $NEW_VERSION"

artifacts:
  files:
    - appspec.yml
    - lambda_dep.zip
